HELP = python main.py -h
ASP-MANUAL = python main.py asp manual
MINIZINC = python main.py minizinc

default:
	@echo Hello there, if you need any help just write make help

help:
	${HELP}

asp-manual:
	${ASP-MANUAL}

minizinc:
	${MINIZINC}